### ISSUE TITLE
BUG: transform_plex_url(request['media'].get('mediaUrl'))

### ISSUE THREAD

**Issue by saschabrockel** [PyroghostX/ForgottenMovies#1]
Hey, great idea, and thank you for this tool and effort.

I don't know what is wrong. My configuration is the following. Is something missing?

```
docker run
  -d
  --name='forgotten-movies'
  --net='unraid'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'TZ'='Europe/Berlin'
  -e 'TAUTULLI_URL'='http://192.168.178.29:8181/api/v2'
  -e 'TAUTULLI_API_KEY'='KEY'
  -e 'OVERSEERR_URL'='http://192.168.178.29:5055/api/v1'
  -e 'OVERSEERR_API_KEY'='KEY='
  -e 'OVERSEERR_NUM_OF_HISTORY_RECORDS'='200'
  -e 'REQUEST_URL'='https://request.xyz.de'
  -e 'THEMOVIEDB_API_KEY'='KEY'
  -e 'SMTP_SERVER'='SMTP'
  -e 'SMTP_PORT'='587'
  -e 'FROM_NAME'='Plex (Sascha)'
  -e 'FROM_EMAIL_ADDRESS'='info@xyz.de'
  -e 'EMAIL_PASSWORD'='password
  -e 'BCC_EMAIL_ADDRESS'='email@gmail.com'
  -e 'ADMIN_NAME'='Admin User'
  -e 'DAYS_SINCE_REQUEST'='90'
  -e 'DAYS_SINCE_REQUEST_EMAIL_TEXT'='3 Monate'
  -e 'HOURS_BETWEEN_EMAILS'='48'
  -e 'JOB_INTERVAL_SECONDS'='3600'
  -e 'INITIAL_DELAY_SECONDS'='600'
  -e 'FLASK_SECRET_KEY'='32 signs secret'
  -e 'LOG_LEVEL'='INFO'
  -e 'DEBUG_MODE'='false'
  -e 'DEBUG_MAX_EMAILS'='2'
  -e 'DEBUG_EMAIL'='xyz@gmail.com'
  -e 'DISABLE_SCHEDULER'='true'
  -e 'restart'='unless-stopped'
  -p '8741:8741/tcp'
  -v '/mnt/cache/appdata/mediaserver/forgotten-movies':'/app/data':'rw'
  --restart=unless-stopped 'pyroghostx/forgottenmovies:latest'
```

The error logs:
```
2025-11-09 21:22:02,297 - INFO - Scheduler process starting (initial delay 600 s, interval 3600 s).
2025-11-09 21:22:22,226 - INFO - Forgotten Movies job triggered (manual).
2025-11-09 21:22:22,227 - INFO - Step 1: Grab requests from Overseerr
2025-11-09 21:22:22,315 - ERROR - Forgotten Movies job raised an exception (manual).
Traceback (most recent call last):
  File "/app/job_runner.py", line 23, in execute_job
    run_forgotten_movies_job()
  File "/app/forgotten_movies.py", line 767, in main
    plex_url, mobile_url = transform_plex_url(request['media'].get('mediaUrl'))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/forgotten_movies.py", line 702, in transform_plex_url
    browser_url = plex_url.replace('#!', 'web/index.html#!')
                  ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
2025-11-09 21:32:02,343 - INFO - Scheduler disabled; skipping automated runs until re-enabled.
```

**Comment by HiroP77** [comment]
got exactly the same problem.

**Comment by PyroghostX** [comment]
Seems like that is an issue with the mediaUrl not being populated from overseerr. I added a safety check so it wont crash. Can you try now?
@saschabrockel @HiroP77 

PS: I didn't have notifications on, now I do so i'll see these

**Comment by saschabrockel** [comment]
@PyroghostX seems to be fixed but I got another error:
```
2025-11-11 20:10:47,905 - INFO - Forgotten Movies job triggered (manual).
2025-11-11 20:10:47,905 - INFO - Step 1: Grab requests from Overseerr
2025-11-11 20:10:48,302 - INFO - Registered email user abc@gmail.com
2025-11-11 20:10:48,672 - INFO - Registered email user def@gmail.com
2025-11-11 20:10:50,974 - ERROR - Forgotten Movies job raised an exception (manual).
Traceback (most recent call last):
  File "/app/job_runner.py", line 23, in execute_job
    run_forgotten_movies_job()
  File "/app/forgotten_movies.py", line 761, in main
    media_added_dt = datetime.fromisoformat(request['media']['mediaAddedAt'][:-1])
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by PyroghostX** [comment]
if we don't have mediaAddedAt then that means its not talking to overseerr correctly. Does it look like this in your compose file?
- OVERSEERR_API_KEY=MTzzMjIzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz2Nz==

I'll code in to check to make sure the api's are working before anything else. 
thanks for helping! I just did happy path, always need other people to see the not perfect path
@saschabrockel

**Comment by saschabrockel** [comment]
@PyroghostX full config:

```
docker run
  -d
  --name='forgotten-movies'
  --net='unraid'
  --pids-limit 2048
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="UNRAID-Server"
  -e HOST_CONTAINERNAME="forgotten-movies"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'TZ'='Europe/Berlin'
  -e 'TAUTULLI_URL'='http://192.168.178.29:8181/api/v2'
  -e 'TAUTULLI_API_KEY'='68xxxxxxxxxxxxxxxxx73'
  -e 'OVERSEERR_URL'='http://192.168.178.29:5055/api/v1'
  -e 'OVERSEERR_API_KEY'='MTYxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxNCk='
  -e 'OVERSEERR_NUM_OF_HISTORY_RECORDS'='200'
  -e 'REQUEST_URL'='https://xyz.xyz.de'
  -e 'THEMOVIEDB_API_KEY'='3xxxxxxxxxxxxxxxxxxxxxxxxxxxx5'
  -e 'SMTP_SERVER'='xxxxxxxxx'
  -e 'SMTP_PORT'='587'
  -e 'FROM_NAME'='Plex (Sascha)'
  -e 'FROM_EMAIL_ADDRESS'='ab@xyz.de'
  -e 'EMAIL_PASSWORD'='xxxxxxxxxxxxxxxxxx'
  -e 'BCC_EMAIL_ADDRESS'='email@gmail.com'
  -e 'ADMIN_NAME'='Sascha Brockel'
  -e 'DAYS_SINCE_REQUEST'='90'
  -e 'DAYS_SINCE_REQUEST_EMAIL_TEXT'='3 Monate'
  -e 'HOURS_BETWEEN_EMAILS'='48'
  -e 'JOB_INTERVAL_SECONDS'='3600'
  -e 'INITIAL_DELAY_SECONDS'='600'
  -e 'FLASK_SECRET_KEY'='419cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx777'
  -e 'LOG_LEVEL'='INFO'
  -e 'DEBUG_MODE'='false'
  -e 'DEBUG_MAX_EMAILS'='2'
  -e 'DEBUG_EMAIL'='xyz@xyz.com'
  -e 'DISABLE_SCHEDULER'='true'
  -e 'restart'='unless-stopped'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8741]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/PyroghostX/ForgottenMovies/refs/heads/main/files/logo.png'
  -p '8741:8741/tcp'
  -v '/mnt/cache/appdata/mediaserver/forgotten-movies':'/app/data':'rw'
  --restart=unless-stopped 'pyroghostx/forgottenmovies:latest'
```

So basically yes. But is my URL correct? Do I need the `/api/v1`?

**Comment by PyroghostX** [comment]
@saschabrockel I added api checks before anything else runs
Can you repull and try again 

If the API is bad it will say
2025-11-11 12:19:51,617 - ERROR - OVERSEERR CONNECTION FAILED: 403 Client Error: Forbidden for url: 
2025-11-11 12:19:51,659 - ERROR - TAUTULLI CONNECTION FAILED: 400 Client Error: Bad Request for url: 

if it works it'll say: All external services reachable.

**Comment by saschabrockel** [comment]
@PyroghostX I think this time it worked, but I wonder why every time a different mail address / user was processed:

```
2025-11-11 20:26:31,428 - INFO - Running startup connectivity checks.
2025-11-11 20:26:31,443 - INFO - All external services reachable.
2025-11-11 20:26:31,603 - INFO - Scheduler process starting (initial delay 600 s, interval 3600 s).
2025-11-11 20:26:47,565 - INFO - Forgotten Movies job triggered (manual).
2025-11-11 20:26:47,580 - INFO - Step 1: Grab requests from Overseerr
2025-11-11 20:26:51,289 - INFO - Registered email user xyz@outlook.de
2025-11-11 20:27:19,053 - INFO - Step 2: Update 10 recent titles from Tautulli
2025-11-11 20:27:19,312 - INFO - Deferring email for abc@gmail.com; waiting one scheduler cycle.
2025-11-11 20:27:19,312 - INFO - Forgotten Movies job completed (manual).
```

**Comment by PyroghostX** [comment]
@saschabrockel  Great, did you end up changing the url or key to get it to work since you posted? Because my code change should have just been for troubleshooting. Unless we still are missing mediaadded date, which will be a problem. 

With different users, each time you run it you should see Upcoming Reminders grow. To keep the API calls to tautulli light I only check 10 media items at time. So if on that check all 10 are watched, then Upcoming Reminders won't increase. But if 2 haven't been watched, then those 2 will get added. and it wont email the 1st time something is added to upcoming reminders so you have the chance to select don't send on any media.
You can hit run over and over and it'll get to the point where its processed all of them, it will have emailed each person 1 time, then after that, each run will just be "Skipping email to x; next reminder allowed at 2025-11-13 14:22." and such
Does that answer it? And good questions, i'll have to add this info to the documentation and/or simply the flow

**Comment by saschabrockel** [comment]
@PyroghostX I haven't changed anything. Ah okay. Funny, I should have received an email, but nothing arrived:
```
2025-11-11 20:35:41,408 - INFO - Forgotten Movies job triggered (manual).
2025-11-11 20:35:41,425 - INFO - Step 1: Grab requests from Overseerr
2025-11-11 20:35:41,550 - INFO - Step 2: Update 10 recent titles from Tautulli
2025-11-11 20:35:42,673 - INFO - Sent email to saschabrockel (xyz@gmail.com) via xyz@gmail.com for The Pickup (50769).
2025-11-11 20:35:45,691 - INFO - Forgotten Movies job completed (manual).
2025-11-11 20:36:31,647 - INFO - Scheduler disabled; skipping automated runs until re-enabled.
```

And it would be lovely if I could exclude users somehow (myself). Because I really make some more requests, and it would be annoying.

**Comment by PyroghostX** [comment]
Excluding yourself from emails: You can add yourself to the unsubscribe list on the homepage.

Could you go to your data folder and open your request_data.json with a txt editor. 
Is the mediaAddedDate, createdAt, plexUrl all filled out?

"5": {"id": 1643, "mediaAddedDate": "2025-11-04T06:32:32", "createdAt": "2025-11-06T14:19:43.723938", "tmdbId": "61888", "ratingkey": "87398", "mediaType": "tv show", "plexUsername": "plexuser1", "email": "email1@gmail.com", "plexUrl": "https://plex.example.com/web/index.html#!/server/id/details?key=%2Flibrary%2Fmetadata%211398", "mobilePlexUrl": "plex://server/id/details?key=%2Flibrary%2Fmetadata%2F87398", "posterUrl": "https://image.tmdb.org/t/p/w500/9TcvdOIBEnIDXbLvFUKluRDa3tZ.jpg", "tautulli_watch_date": null, "email_sent": false, "skip_email": false, "eligible_for_email": false, "title": "Unknown"}, "6": {"id": 1642, "mediaAddedDate": "2025-11-04T02:09:56", "createdAt": "2025-11-06T14:19:43.782794", "tmdbId": "997113", "ratingkey": "87392", "mediaType": "movie", "plexUsername": "plexuser2", "email": "email2@gmail.com", "plexUrl": "https://plex.example.com/web/index.html#!/server/id/details?key=%2Flibrary%2Fmetadata%2F87392", "mobilePlexUrl": "plex://server/id/details?key=%2Flibrary%2Fmetadata%2F8112", "posterUrl": "https://image.tmdb.org/t/p/w500/ecflk7AZf0ij205yDswjlvdxlCO.jpg", "tautulli_watch_date": null, "email_sent": false, "skip_email": false, "eligible_for_email": false, "title": "Unknown"}, 


And i'll need to add checks for the email sending as well, if that isn't setup right it will silently fail. - EDIT: It will actually give a useful error: smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted.

So it's not your email settings... and if you check the sent mail from the email you have configured as the from address. It doesn't show?

**Comment by HiroP77** [comment]
again same here, overall problem is fixed (and i havend chamged anything in my config), but no mails.
jequest_data.json showes filled fields for mediaAddedDate and createdAt; but plexUrl is always  "plexUrl": null, "mobilePlexUrl": null, "

**Comment by PyroghostX** [comment]
I haven't been able to reproduce the issue yet, I set one of my entries to null plexurl and it still sent the email, so that shouldn't be the problem:
"149": {"id": 1457, "mediaAddedDate": "2025-07-10T20:12:01", "createdAt": "2025-11-11T12:45:21.421293", "tmdbId": "615469", "ratingkey": "83024", "mediaType": "movie", "plexUsername": "user1", "email": "email1@gmail.com", "plexUrl": "null", "mobilePlexUrl": "null", "posterUrl": "https://image.tmdb.org/t/p/w500/7COPO5B9AOKIB4sEkvNu0wfve3c.jpg", "tautulli_watch_date": null, "email_sent": true, "skip_email": false, "eligible_for_email": true, "title": "Spiderhead"},

Not sure what the problem is.

@HiroP77 I have added more debugging to the email send code. can you pull the new version and in your config set DEBUG_MODE=true and make sure DEBUG_EMAIL is set

**Comment by saschabrockel** [comment]
@PyroghostX still no mail:

```
2025-11-11 22:34:40,782 - DEBUG - Refreshed default email template at /app/data/email_template_original.html
2025-11-11 22:34:40,784 - DEBUG - Preparing email send for request 722: recipient=abc@outlook.de, subject=Plex Reminder: Your Name. - Gestern, heute und für immer is available and unwatched, rating_key=46875, media_type=movie
2025-11-11 22:34:40,784 - DEBUG - send_email invoked for abc@outlook.de (subject=Plex Reminder: Your Name. - Gestern, heute und für immer is available and unwatched, html=True).
2025-11-11 22:34:40,784 - INFO - Debug email mode enabled; redirecting email originally for abc@outlook.de to xyz@gmail.com.
2025-11-11 22:34:40,784 - DEBUG - Connecting to SMTP server ssl.xxx.net:587 as info@xyz.de.
2025-11-11 22:34:40,905 - DEBUG - SMTP connection established, issuing STARTTLS.
2025-11-11 22:34:41,027 - DEBUG - STARTTLS negotiation succeeded; logging in.
2025-11-11 22:34:41,301 - DEBUG - SMTP login succeeded; sending message to xyz@gmail.com.
2025-11-11 22:34:41,842 - DEBUG - SMTP NOOP succeeded after send.
2025-11-11 22:34:41,856 - DEBUG - Email sent successfully to xyz@gmail.com.
2025-11-11 22:34:41,857 - INFO - Sent email to lala.44 (abc@outlook.de) via xyz@gmail.com for Your Name. - Gestern, heute und für immer (46875).
2025-11-11 22:34:41,857 - INFO - Debug mode active; skipped persisting send for abc@outlook.de.
2025-11-11 22:34:41,857 - INFO - Skipped persisting send for lala.44 (46875) due to debug mode.
2025-11-11 22:34:41,857 - INFO - Forgotten Movies job completed (manual).
2025-11-11 22:34:41,857 - DEBUG - Attempting to release lock 23016246186432 on /app/data/job.lock
2025-11-11 22:34:41,857 - DEBUG - Lock 23016246186432 released on /app/data/job.lock
```

**Comment by HiroP77** [comment]
ah, got it sorted out, now it works for me. Emails are delivered.
My mistake was a " ' " at the debug-Email-adress, was handled as a illegal character.

**Comment by PyroghostX** [comment]
@HiroP77 Thats good news email is working.

@saschabrockel It's got to be your email not allowing it or something, specially since hiro worked. you are using at outlook email in 1 of them? did you test with gmail on both sides (sending and receiving?) 
Trying to think what else to test

**Comment by PyroghostX** [comment]
@HiroP77 with Plex url being null that means the email won't be able to populate it. Do you have the Web App url set on https://request.example.com/settings/plex overseerr plex settings page?

**Comment by saschabrockel** [comment]
@HiroP77, what is your exact config? My sender mail is my own domain, but never ever caused problems. I tried it with Healthchecks again, for example. I have no idea what the problem is.

@PyroghostX, it feels like it's a false positive for me. Can we debug the log more for the emails? It will always say successful... I tried port 465 and it failed. It's more weird because the connection seems to be valid.

**Comment by PyroghostX** [comment]
@saschabrockel I just created a new gmail account to test with, and confirmed it works, here is the info to put in and trigger an email, reply back once you trigger one and I'll check if it sent to itself

      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - FROM_NAME="Plex Forgotten Movies"
      - FROM_EMAIL_ADDRESS=redacted
      - EMAIL_PASSWORD=redacted
      - BCC_EMAIL_ADDRESS=redacted #Optional, if you want to get any emails this sends
      - DEBUG_MODE=true
      - DEBUG_EMAIL=redacted
      - DEBUG_MAX_EMAILS=2

I have it setup so it doesn't send any personal info:

<img width="491" height="446" alt="Image" src="https://github.com/user-attachments/assets/7ebdefcb-35fc-4009-9053-60fbbd3f29a6" />

**Comment by HiroP77** [comment]
> [@HiroP77](https://github.com/HiroP77), what is your exact config? My sender mail is my own domain, but never ever caused problems. I tried it with Healthchecks again, for example. I have no idea what the problem is.
I just took the vanilla-config:


    forgotten-movies:
      image: pyroghostx/forgottenmovies:latest
      container_name: forgotten-movies
      restart: unless-stopped
      environment:
        - ROOT="/mnt/DOCKER-CONFIGS/FORGOTTENMOVIES"
        - PUID=1000 # default user id, defined in .env
        - PGID=1000 # default group id, defined in .env
        - TZ=Europe/Berin # timezone, defined in .env
        - TAUTULLI_URL=https://tautulli.DOMAIN.de/api/v2 
        - TAUTULLI_API_KEY=eb8ca41saltsaltd6fb37
        - OVERSEERR_URL=https://overseerr.DOMAIN.de/api/v1
        - OVERSEERR_API_KEY=MTcwMsaltsaltlYmVlMzZkNGJjNg==
        - OVERSEERR_NUM_OF_HISTORY_RECORDS=200 #Set this to how many requests to pull from overseerr, base it on how many youve gotten in the last 3-4 months.
        - REQUEST_URL=https://overseerr.DOMAIN.de
        - THEMOVIEDB_API_KEY=ad01saltsalt1a6b4f6f
        - SMTP_SERVER=smtp.strato.de
        - SMTP_PORT=587
        - FROM_NAME="Plex Forgotten Movies"
        - FROM_EMAIL_ADDRESS=user@DOMAIN.de
        - EMAIL_PASSWORD=YMsaltsalt 
        - BCC_EMAIL_ADDRESS=user@DOMAIN.de 
        - ADMIN_NAME=HiroP # What name in the email do you want shown
        - DAYS_SINCE_REQUEST=90 # How old should a request be until we email them about it
        - DAYS_SINCE_REQUEST_EMAIL_TEXT=3 months # Human readable of DAYS_SINCE_REQUEST for the email text
        - HOURS_BETWEEN_EMAILS=168 # How often to send an email to each person, 168 hours = 1 week is default
        - JOB_INTERVAL_SECONDS=3600 # How often it runs and checks for unwatched media, 3600 seconds (1 hour) is default
        - INITIAL_DELAY_SECONDS=300 # How long to wait after the app starts to check, gives you time to unsubscribe emails before it sends anything
        - FLASK_SECRET_KEY=496417ef8a55d3d6272ece4asaltsalt35080e4472fb3c81241 
        - LOG_LEVEL=INFO
        - DEBUG_MODE=false #when this is true, the app will email the debug email instead of users, so you can use it for testing
        - DEBUG_MAX_EMAILS=2 #so it doesn't email you over and over, it will email 2 times
        - DEBUG_EMAIL=user@DOMAIN.de 
        - DISABLE_SCHEDULER=false #this will have the scheduler start disabled, so it won't hit api's or email people
      ports:
        - "8741:8741"
      volumes:
        - /mnt/DOCKER-CONFIGS/FORGOTTENMOVIES:/app/data  # Persist data outside the container

**Comment by HiroP77** [comment]
> [@HiroP77](https://github.com/HiroP77) with Plex url being null that means the email won't be able to populate it. Do you have the Web App url set on https://request.example.com/settings/plex overseerr plex settings page?

Ah, you are correct, i never set it! Now, with it set, it even populates the correct url.

**Comment by saschabrockel** [comment]
@PyroghostX I can confirm that it works with Gmail, but not with my own domain. Is it possible, even though it says connected and sent, that the tool cannot handle special characters in the password?

Another thing that is not working as expected is the `SMTP_PORT`. When I change it to `465`, it will fail because it still seems to try to use STARTTLS. It should also work with SSL and is the main example for OVH, even though I normally also use STARTTLS: https://help.ovhcloud.com/csm/de-mx-plan-outlook-windows-configuration?id=kb_article_view&sysparm_article=KB0052096

And where should the `ADMIN_NAME` appear? I saw it nowhere in my mail.

**Comment by PyroghostX** [comment]
@saschabrockel 
I removed ADMIN_NAME from the default template, so its currently not used, but if wanted you could add it back into the email with {{ ADMIN_NAME }}.

I have pushed an update to image: pyroghostx/forgottenmovies:v0.2.3 config, I didn't push this to :latest, until you confirm it works, it should log a bit more
Are you putting your password in quotes? "password"

**Comment by PyroghostX** [comment]
@saschabrockel Had a chance to test the image?

**Comment by saschabrockel** [comment]
@PyroghostX, sorry, I tested it now. I don't see more logs. My own email domain still does not work.

```
2025-11-22 00:21:55,587 - DEBUG - watch_history: []
2025-11-22 00:21:55,587 - DEBUG - Starting new HTTP connection (1): 192.168.178.29:8181
2025-11-22 00:21:55,599 - DEBUG - http://192.168.178.29:8181 "GET /api/v2?apikey=APIKEY&cmd=get_metadata&rating_key=51640 HTTP/1.1" 200 1716
2025-11-22 00:21:55,599 - DEBUG - title: Hellhound
2025-11-22 00:21:55,607 - INFO - Deferring email for user1@gmail.com; waiting one scheduler cycle.
2025-11-22 00:21:55,610 - INFO - Deferring email for user2@gmail.com; waiting one scheduler cycle.
2025-11-22 00:21:55,611 - DEBUG - Starting new HTTP connection (1): 192.168.178.29:8181
2025-11-22 00:21:55,619 - DEBUG - http://192.168.178.29:8181 "GET /api/v2?apikey=APIKEY&cmd=get_history&user=xxx.44&length=1&rating_key=46875 HTTP/1.1" 200 138
2025-11-22 00:21:55,619 - DEBUG - watch_history: []
2025-11-22 00:21:55,620 - DEBUG - Refreshed default email template at /app/data/email_template_original.html
2025-11-22 00:21:55,621 - DEBUG - Preparing email send for request 722: recipient=xyz@outlook.de, subject=Plex Reminder: Your Name. - Gestern, heute und für immer is available and unwatched, rating_key=46875, media_type=movie
2025-11-22 00:21:55,621 - DEBUG - send_email invoked for xyz@outlook.de (subject=Plex Reminder: Your Name. - Gestern, heute und für immer is available and unwatched, html=True).
2025-11-22 00:21:55,622 - INFO - Debug email mode enabled; redirecting email originally for xyz@outlook.de to debugmail@gmail.com.
2025-11-22 00:21:55,622 - DEBUG - Connecting to SMTP server smtp.mail.ovh.net:465 as info@mydomain.de using SSL.
2025-11-22 00:21:55,814 - DEBUG - Implicit SSL/TLS connection established; logging in.
2025-11-22 00:21:55,938 - DEBUG - SMTP login succeeded; sending message to debugmail@gmail.com.
2025-11-22 00:21:56,373 - DEBUG - SMTP NOOP succeeded after send.
2025-11-22 00:21:56,399 - DEBUG - Email sent successfully to debugmail@gmail.com.
2025-11-22 00:21:56,399 - INFO - Sent email to xxx.44 (xyz@outlook.de) via debugmail@gmail.com for Your Name. - Gestern, heute und für immer (46875).
2025-11-22 00:21:56,399 - INFO - Debug mode active; skipped persisting send for xyz@outlook.de.
2025-11-22 00:21:56,399 - INFO - Skipped persisting send for xxx.44 (46875) due to debug mode.
2025-11-22 00:21:56,399 - INFO - Forgotten Movies job completed (manual).
2025-11-22 00:21:56,399 - DEBUG - Attempting to release lock 22972848492032 on /app/data/job.lock
2025-11-22 00:21:56,399 - DEBUG - Lock 22972848492032 released on /app/data/job.lock
``` 

Tried another one, but still no mail arriving:
```
2025-11-22 00:31:33,885 - DEBUG - send_email invoked for user1@gmail.com (subject=Plex Reminder: Fist of the Warrior is available and unwatched, html=True).
2025-11-22 00:31:33,885 - INFO - Debug email mode enabled; redirecting email originally for user1@gmail.com to debugmail@gmail.com.
2025-11-22 00:31:33,885 - DEBUG - Connecting to SMTP server ssl0.ovh.net:587 as info@mydomain.de using STARTTLS.
2025-11-22 00:31:33,979 - DEBUG - SMTP connection established, issuing STARTTLS.
2025-11-22 00:31:34,051 - DEBUG - STARTTLS negotiation succeeded; logging in.
2025-11-22 00:31:34,385 - DEBUG - SMTP login succeeded; sending message to debugmail@gmail.com.
2025-11-22 00:31:34,868 - DEBUG - SMTP NOOP succeeded after send.
2025-11-22 00:31:34,886 - DEBUG - Email sent successfully to debugmail@gmail.com.
2025-11-22 00:31:34,887 - INFO - Sent email to User1 (user1@gmail.com) via debugmail@gmail.com for Fist of the Warrior (51899).
```

My password does not include a quote. Unraid single-quotes the password always while starting when you scroll a bit to my previous posts. It's like this.

**Comment by saschabrockel** [comment]
@PyroghostX even this the latest version I don't know why it does not work...

**Comment by PyroghostX** [comment]
@saschabrockel yeah im not sure what else to try. It makes it hard to test since I dont have an outlook custom domain. Either I would have to set one up to test it, or you would have to download the code and do troubleshooting, other than that i'm not sure how to get to the bottom of the issue
